"""create_message_tasks_table

Revision ID: 01a2b3c4d5e6
Revises: 2b231de97dc3
Create Date: 2023-12-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a2b3c4d5e6'
down_revision = '2b231de97dc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('message_text', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), default=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_tasks')
    # ### end Alembic commands ### 